language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

#before_script:
#  - export PYTHONPATH=/home/travis/build/yhaidai/epam-python-winter-2021-final-project/department_app/

script:
  - pylint clinic_app
  - coverage run -m unittest discover tests
  - coverage report

after_success:
  - coveralls