language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS clinic_test;'


script:
  - pylint clinic_app
  - coverage run -m unittest discover tests
  - coverage report

#after_success:
#  - coveralls