"""empty message

Revision ID: 1353d102524b
Revises: 20847e48a568
Create Date: 2021-12-14 02:26:48.802003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1353d102524b'
down_revision = '20847e48a568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('last_modified', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('appointment', 'last_update')
    op.add_column('doctor', sa.Column('last_modified', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('doctor', 'last_update')
    op.add_column('patient', sa.Column('last_modified', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('patient', 'last_update')
    op.add_column('user', sa.Column('last_modified', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user', 'last_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('user', 'last_modified')
    op.add_column('patient', sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('patient', 'last_modified')
    op.add_column('doctor', sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('doctor', 'last_modified')
    op.add_column('appointment', sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('appointment', 'last_modified')
    # ### end Alembic commands ###
