"""empty message

Revision ID: dc94c9d563a4
Revises: 
Create Date: 2021-12-11 00:09:53.897244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc94c9d563a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=127, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('speciality', sa.String(length=127, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('info', sa.String(length=1023, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_uuid'), 'doctor', ['uuid'], unique=True)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=40, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('name', sa.String(length=40, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('patronymic', sa.String(length=40, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_phone_number'), 'patient', ['phone_number'], unique=True)
    op.create_index(op.f('ix_patient_surname'), 'patient', ['surname'], unique=False)
    op.create_index(op.f('ix_patient_uuid'), 'patient', ['uuid'], unique=True)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('conclusion', sa.String(length=511), nullable=True),
    sa.Column('prescription', sa.String(length=511), nullable=True),
    sa.Column('bill', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'date', 'time'),
    sa.UniqueConstraint('patient_id', 'date', 'time')
    )
    op.create_index(op.f('ix_appointment_date'), 'appointment', ['date'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_uuid'), 'appointment', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=127), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_doctor_id'), 'user', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_doctor_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_appointment_uuid'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_date'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_patient_uuid'), table_name='patient')
    op.drop_index(op.f('ix_patient_surname'), table_name='patient')
    op.drop_index(op.f('ix_patient_phone_number'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctor_uuid'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
