"""empty message

Revision ID: e0a8bcac6604
Revises: dc94c9d563a4
Create Date: 2021-12-13 23:06:59.392457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a8bcac6604'
down_revision = 'dc94c9d563a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('last_update', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'last_update')
    # ### end Alembic commands ###
